# Mudar o prefixo de Ctrl+b para Ctrl+a (Atualmente configurado para Alt+v)
# Remove o prefixo padrão
unbind C-b

# Define o Alt + v como novo prefixo
set -g prefix M-v
bind M-v send-prefix

# Usar | para dividir verticalmente e - para horizontal
bind | split-window -h
bind - split-window -v

# Remover os atalhos antigos de divisão
unbind '"'
unbind %

set -g mouse on

# Lista de plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'dracula/tmux'

# Habilita a restauração automática do continuum
set -g @continuum-restore 'on'

# Tema Dracula e configurações
set -g @dracula-show-powerline true
set -g @dracula-plugins "cpu-usage ram-usage time"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session

# Inicializa o gerenciador de plugins (MANTENHA ESTA LINHA NO FIM DO ARQUIVO)
run '~/.tmux/plugins/tpm/tpm'
