# PREFIXO E CONFIGURAÇÕES BÁSICAS
unbind C-b
set -g prefix M-v
bind M-v send-prefix

set -g mouse on

# DIVISÕES DE TELA
unbind '"'
unbind %
bind _ split-window -h
bind - split-window -v

# PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'dracula/tmux'

# --- CONFIGURAÇÕES DE CÓPIA (TECLADO) ---
# Ativa atalhos do Vim para navegação
setw -g mode-keys vi
# Impede que o mouse cancele a seleção ou dê problemas de rolagem
unbind -T copy-mode-vi MouseDragEnd1Pane

# CONFIGURAÇÃO DOS PLUGINS
set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'

set -g @dracula-show-powerline true
set -g @dracula-plugins "cpu-usage ram-usage time"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session

# INICIALIZAÇÃO DO TPM (SEMPRE NO FINAL)
run '~/.tmux/plugins/tpm/tpm'

# Recarregar o arquivo de configuração com Prefixo + r
bind r source-file ~/.tmux.conf \; display "Configuração do Tmux Recarregada!"

# Ativar/desativar sincronização de painéis com Prefixo + S (S maiúsculo)
bind S set-window-option synchronize-panes \; display-message "Sincronização de painéis alternada!"
